server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/vacation;
    username: vacation
    password: vacation
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace