server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://52.78.130.4:5432/vacance
    username: vacance
    password: vacance

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace